# Generated by Django 3.1.5 on 2021-01-15 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='news.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscrition',
            name='category',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
    ]
