# Generated by Django 3.1.5 on 2021-01-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210115_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publication_date',
        ),
    ]
