# Generated by Django 3.1.5 on 2021-01-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210115_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
    ]
