# Generated by Django 3.1.5 on 2021-01-15 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210115_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscrition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
    ]
